### ISSUE TITLE
[EPIC] Rebuild the old CLI

### ISSUE THREAD

**Issue by SchoolGuy** [cobbler/cli#21]
This is the "Epic" to collect the effort of how complete the new CLI is atm:

- [x] https://github.com/cobbler/cli/issues/8
- [x] https://github.com/cobbler/cli/issues/10
- [x] https://github.com/cobbler/cli/issues/11
- [x] https://github.com/cobbler/cli/issues/12
- [x] https://github.com/cobbler/cli/issues/13
- [x] https://github.com/cobbler/cli/issues/14
- [x] https://github.com/cobbler/cli/issues/15
- [x] https://github.com/cobbler/cli/issues/16
- [x] https://github.com/cobbler/cli/issues/17
- [x] https://github.com/cobbler/cli/issues/18

All issues apart from these here are already improvements over the old CLI.
